# Copyright 2014 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
--- 
imports: 
  - path: config.jinja
resources: 
  - 
    name: loader
    type: config.jinja
    properties: 
      target: http://107.178.252.126/
      output_bucket: gs://gce-ilb-load
      date_prefix: "20150812"
      image: https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/debian-8-jessie-v20150710
      test_duration: 90m
      region: us-central1
      machine_type: 
        loader: n1-highcpu-16
      zones: 
        us-central1-b: 
          loader_servers: 3
        us-central1-c: 
          loader_servers: 3
        us-central1-f: 
          loader_servers: 3
